apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-api
  namespace: nexusagent-prod
  labels:
    app.kubernetes.io/name: nexusagent
    app.kubernetes.io/component: platform-api
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-console
  namespace: nexusagent-prod
  labels:
    app.kubernetes.io/name: nexusagent
    app.kubernetes.io/component: web-console
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nexus-internal
  namespace: nexusagent-prod
  labels:
    app.kubernetes.io/name: nexusagent
    app.kubernetes.io/component: internal-services
automountServiceAccountToken: false
